[package]
name = "block-stm-revm"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = "0.7.2"
alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy", rev = "07611cfc9f277dc5bbfd7d21e9d70ad37b441a51" }
dashmap = "5.5.3"
stacker = "0.1.15"

# Let's do our best to port needed REVM changes upstream
revm = { git = "https://github.com/risechain/revm", rev = "58a126a0a3b586cb97943358deb1285e5dc9fefc" }

# RPC Storage dependencies
# TODO: Put these behind an RPC flag to not pollute the core
# library with RPC network & transport dependencies, etc.
alloy-provider = { git = "https://github.com/alloy-rs/alloy", rev = "07611cfc9f277dc5bbfd7d21e9d70ad37b441a51" }
alloy-transport = { git = "https://github.com/alloy-rs/alloy", rev = "07611cfc9f277dc5bbfd7d21e9d70ad37b441a51" }
alloy-transport-http = { git = "https://github.com/alloy-rs/alloy", rev = "07611cfc9f277dc5bbfd7d21e9d70ad37b441a51" }
reqwest = "0.12.4"
tokio = "1.37.0"

[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.5"
rayon = "1.10.0"
revme = { git = "https://github.com/risechain/revm", rev = "58a126a0a3b586cb97943358deb1285e5dc9fefc" }
serde = "1.0.202"
serde_json = { version = "1.0.116" }
walkdir = "2.5.0"

[lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.unreachable_pub = "warn"

[[bench]]
name = "mainnet"
harness = false
