[package]
name = "block-stm-revm"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "5.5.3"
rand = "0.8.5"
rayon = "1.10.0"
# TODO: Let's do our best to port needed changes upstream
revm = { git = "https://github.com/risechain/revm", rev = "626fe267f13347cf60407cf11fc947661abe774b" }
revme = { git = "https://github.com/risechain/revm", rev = "626fe267f13347cf60407cf11fc947661abe774b" }
serde_json = { version = "1.0.116" }
stacker = "0.1.15"
walkdir = "2.5.0"

[lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.unreachable_pub = "warn"
