[package]
name = "block-stm-revm"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = "0.7.2"
alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy", rev = "dd25769df2089063e84a557c6844d20fba2eb315" }
dashmap = "5.5.3"
rand = "0.8.5"
rayon = "1.10.0"
# TODO: Let's do our best to port needed changes upstream
revm = { git = "https://github.com/risechain/revm", rev = "d4a99ded7a2a8e131e28e7aa4f07c49999b88e29" }
revme = { git = "https://github.com/risechain/revm", rev = "d4a99ded7a2a8e131e28e7aa4f07c49999b88e29" }
serde_json = { version = "1.0.116" }
stacker = "0.1.15"
walkdir = "2.5.0"

[lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.unreachable_pub = "warn"
