[package]
name = "block-stm-revm"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "5.5.3"
rand = "0.8.5"
# TODO: Let's do our best to port needed changes upstream
revm = { git = "https://github.com/risechain/revm", rev = "b3c7ef930bf7fbb5ed08ba3dc69070bdb50c614c" }
revme = { git = "https://github.com/risechain/revm", rev = "b3c7ef930bf7fbb5ed08ba3dc69070bdb50c614c" }
serde_json = { version = "1.0.116" }

[lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.unreachable_pub = "warn"
