[package]
name = "pevm"
version = "0.1.0"
edition = "2021"

[dependencies]
# Put this behind a feature flag if there are use cases & users
# that need more security guarantees even for internally hashing
# EVM memory locations (we do not persist these hashes).
ahash = "0.8.11"
alloy-primitives = { version = "0.7.4", features = ["asm-keccak"] }
alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy", rev = "64feb9bc51c8021ea08535694c44de84222f474e" }
crossbeam = "0.8.4"
dashmap = "5.5.3"

# Let's do our best to port needed REVM changes upstream
revm = { git = "https://github.com/risechain/revm", rev = "f473fb17f127a8ead2bccc42e9ffb97da55766dc", features = [
    "serde",
] }

# RPC Storage dependencies
# TODO: Put these behind an RPC flag to not pollute the core
# library with RPC network & transport dependencies, etc.
alloy-provider = { git = "https://github.com/alloy-rs/alloy", rev = "64feb9bc51c8021ea08535694c44de84222f474e" }
alloy-transport = { git = "https://github.com/alloy-rs/alloy", rev = "64feb9bc51c8021ea08535694c44de84222f474e" }
alloy-transport-http = { git = "https://github.com/alloy-rs/alloy", rev = "64feb9bc51c8021ea08535694c44de84222f474e" }
reqwest = "0.12.4"
tokio = { version = "1.37.0", features = ["rt-multi-thread"] }

[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.5"
rayon = "1.10.0"
revme = { git = "https://github.com/risechain/revm", rev = "f473fb17f127a8ead2bccc42e9ffb97da55766dc" }
serde = "1.0.202"
serde_json = "1.0.117"
snmalloc-rs = "0.3.5"
walkdir = "2.5.0"

[lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.unreachable_pub = "warn"

[[bench]]
name = "mainnet"
harness = false

[[bench]]
name = "gigagas"
harness = false

[profile.release]
codegen-units = 1
panic = "abort"
lto = "fat"
