name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo clippy --all-targets --all-features

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Our tests are heavy, avoid running them in parallel to not risk nuking RAM.
      # Each parallel test still executes parallelly up to the number of CPUs anyway.
      - run: |
          git submodule update --init
          cargo test --release -- --test-threads=1
